ignored_colors = [
    #000000, # filter black, DO NOT USE "#"!!!
]
allowed_colors = ["6D001A", "BE0039", "FF4500", "FFA800", "FFD635", "FFF8B8", "00A368", "00CC78", "7EED56", "00756F", "009EAA", "00CCC0", "2450A4", "3690EA", "51E9F4", "493AC1", "6A5CFF", "94B3FF", "811E9F", "B44AC0", "E4ABFF", "DE107F", "FF3881", "FF99AA", "6D482F", "9C6926", "FFB470", "000000", "515252", "898D90", "D4D7D9", "FFFFFF"]

width = 3000
height = 2000
add-x = 1500
add-y = 1000

default_prio = 120 # priority: higher number = higher chance of being placed

# example:
# [[structure]]
# name = "name"
# file = "name.png"
# priority_file = "flagge-ost_prio.png"
# startx = 1332
# starty = 1122
# priority = 127
# overlay_only = false
# prio_in_picture = false

[[structure]]
name = "end"
file = "end.png"
startx = -1500
starty = -1000
priority = 127