ignored_colors = [
    #000000, # filter black, DO NOT USE "#"!!!
]
allowed_colors = ["6D001A", "BE0039", "FF4500", "FFA800", "FFD635", "FFF8B8", "00A368", "00CC78", "7EED56", "00756F", "009EAA", "00CCC0", "2450A4", "3690EA", "51E9F4", "493AC1", "6A5CFF", "94B3FF", "811E9F", "B44AC0", "E4ABFF", "DE107F", "FF3881", "FF99AA", "6D482F", "9C6926", "FFB470", "000000", "515252", "898D90", "D4D7D9", "FFFFFF"]

width = 3000
height = 2000
add-x = 1500
add-y = 1000

default_prio = 120 # priority: higher number = higher chance of being placed

# example:
# [[structure]]
# name = "name"
# file = "name.png"
# priority_file = "flagge-ost_prio.png"
# startx = 1332
# starty = 1122
# priority = 127
# overlay_only = false
# prio_in_picture = false


[[structure]]
name = "techno_memorial_1"
file = "techno_memorial_1.png"
startx = 490
starty = -296
priority = 127

[[structure]]
name = "techno_memorial_2"
file = "techno_memorial_2.png"
startx = -215
starty = 241
priority = 127

[[structure]]
name = "perry"
file = "perry.png"
startx = -95
starty = 176
priority = 127

[[structure]]
name = "gronkh"
file = "gronkh.png"
startx = 211
starty = -368
priority = 127

[[structure]]
name = "shrek"
file = "shrek.png"
startx = 172
starty = -797
priority = 127

[[structure]]
name = "gemaelde"
file = "gemaelde.png"
startx = -111
starty = 587
priority = 127

[[structure]]
name = "reezeschwein"
file = "reezeschwein.png"
startx = 55
starty = 737
priority = 127

[[structure]]
name = "rvd"
file = "rvd.png"
startx = 16
starty = 573
priority = 127

[[structure]]
name = "kewin"
file = "kewin.png"
startx = -1499
starty = -753
priority = 127

[[structure]]
name = "kewin_border"
file = "kewin_border.png"
startx = -1500
starty = -754
priority = 127

[[structure]]
name = "glp"
file = "glp.png"
startx = -830
starty = 409
priority = 127

[[structure]]
name = "oneplace_1"
file = "oneplace_1.png"
startx = -1500
starty = -247
priority = 127

[[structure]]
name = "pokemon"
file = "pokemon.png"
startx = 1001
starty = -963
priority = 127

[[structure]]
name = "oneplace_2"
file = "oneplace_2.png"
startx = 1284
starty = 395
priority = 127

[[structure]]
name = "fuckspezlarge2"
file = "fuckspezlarge2.png"
startx = -1500
starty = -1000
priority = 127
