ignored_colors = [
    #000000, # filter black, DO NOT USE "#"!!!
]
allowed_colors = [
    #000000, # allow black, DO NOT USE "#"!!!
    "FF4500",
    "FFA800",
    "FFD635",
    "00A368",
    "7EED56",
    "2450A4",
    "3690EA",
    "51E9F4",
    "811E9F",
    "B44AC0",
    "FF99AA",
    "9C6926",
    "000000",
    "898D90",
    "D4D7D9",
    "FFFFFF"
]
width = 2000
height = 2000
add-x = 1000
add-y = 1000

default_prio = 120 # priority: higher number = higher chance of being placed

# example:
# [[structure]]
# name = "flagge-ost"
# file = "flagge-ost.png"
# priority_file = "flagge-ost_prio.png"
# startx = 1332
# starty = 1122
# priority = 127
# overlay_only = false
# prio_in_picture = false

# FROM LEFT TO RIGHT
[[structure]]
name = "techno-memorial1"
file = "techno-22-07-23-4_21PM.png"
startx = 490
starty = -290
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "techno-memorial2"
file = "techno-memorial2-22-07-2023-4_55PM.png"
startx = -215
starty = 242
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "pixelperry"
file = "pixelperry-v2.png"
startx = -95
starty = 176
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "spanisch"
file = "spanisch.png"
startx = -1000
starty = 332
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "gronkh"
file = "gronkh_und_co.png"
startx = 211
starty = -368
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "shrek"
file = "shrek.png"
startx = 199
starty = -783
priority = 127
