ignored_colors = [
    #000000, # filter black, DO NOT USE "#"!!!
]
allowed_colors = [
    "000000", # allow black, DO NOT USE "#"!!!
    "BE0039",
    "FF4500",
    "FFA800",
    "FFD635",
    "00A368",
    "00CC78",
    "7EED56",
    "00756F",
    "009EAA",
    "2450A4",
    "3690EA",
    "51E9F4",
    "493AC1",
    "6A5CFF",
    "811E9F",
    "B44AC0",
    "FF3881",
    "FF99AA",
    "6D482F",
    "9C6926",
    "898D90",
    "D4D7D9",
    "FFFFFF"
]
width = 3000
height = 2000
add-x = 1500
add-y = 1000

default_prio = 120 # priority: higher number = higher chance of being placed

# example:
# [[structure]]
# name = "flagge-ost"
# file = "flagge-ost.png"
# priority_file = "flagge-ost_prio.png"
# startx = 1332
# starty = 1122
# priority = 127
# overlay_only = false
# prio_in_picture = false

# FROM LEFT TO RIGHT
[[structure]]
name = "techno-memorial1"
file = "techno-22-07-23-4_21PM.png"
startx = 490
starty = -290
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "techno-memorial2"
file = "techno-memorial2-22-07-2023-4_55PM.png"
startx = -215
starty = 242
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "pixelperry"
file = "pixelperry-v2.png"
startx = -95
starty = 176
priority = 127

# # FROM LEFT TO RIGHT
# [[structure]]
# name = "spanisch"
# file = "spanisch.png"
# startx = -1000
# starty = 332
# priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "gronkh"
file = "gronkh_und_co.png"
startx = 211
starty = -368
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "shrek"
file = "shrek.png"
startx = 172
starty = -796
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "gemaelde"
file = "gemaelde.png"
startx = -111
starty = 587
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "reezeschwein"
file = "reezeschwein.png"
startx = 55
starty = 737
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "rvd"
file = "rvd.png"
startx = 16
starty = 573
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "rosin"
file = "rosin.png"
startx = -109
starty = 902
priority = 127

# FROM LEFT TO RIGHT
[[structure]]
name = "kewin"
file = "kewin.png"
startx = -1499
starty = -753
priority = 127
disabled = false

# FROM LEFT TO RIGHT
[[structure]]
name = "kewinborder"
file = "kewin-border.png"
startx = -1500
starty = -754
priority = 127
disabled = false

# FROM LEFT TO RIGHT
[[structure]]
name = "glp"
file = "glp.png"
startx = -830
starty = 405
priority = 127
disabled = false

# FROM LEFT TO RIGHT
[[structure]]
name = "oneplace1"
file = "oneplace-1.png"
startx = -1500
starty = -248
priority = 127
disabled = false

# FROM LEFT TO RIGHT
[[structure]]
name = "pokemon"
file = "pokemon.png"
startx = 1001
starty = -963
priority = 127
disabled = false